require:
  - rubocop
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/*

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/LineLength:
  Exclude:
    - db/**/*

# This is too aggressive with our use of Seattle.rb style lack of parens on method calls
# E.g., return redirect_to [:articles]
# Rubocop thinks that `redirect_to` is a collection and `:articles` is a hash key
Layout/SpaceBeforeBrackets:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/I18nLocaleTexts:
  Enabled: false

Rails/TimeZone:
  Exclude:
    - script/*

RSpec/MessageSpies:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: consistent

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - script/*

Style/OpenStructUse:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/StabbyLambdaParentheses:
  EnforcedStyle: require_no_parentheses
