inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/*'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/LineLength:
  Exclude:
    - 'db/**/*'

# This is too aggressive with our use of Seattle.rb style lack of parens on method calls
# E.g., return redirect_to [:articles]
# Rubocop thinks that `redirect_to` is a collection and `:articles` is a hash key
Layout/SpaceBeforeBrackets:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - config/environments/*.rb

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/TimeZone:
  Exclude:
    - 'script/*'

RSpec/MessageSpies:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    - 'script/*'

Style/RedundantFetchBlock:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/HashSyntax:
  Enabled: false
