require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/audios' do
  # This should return the minimal set of attributes required to create a valid
  # Audio. As you add validations to Audio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Audio.create! valid_attributes
      get audios_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      audio = Audio.create! valid_attributes
      get audio_url(audio)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_audio_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      audio = Audio.create! valid_attributes
      get edit_audio_url(audio)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Audio' do
        expect do
          post audios_url, params: { audio: valid_attributes }
        end.to change(Audio, :count).by(1)
      end

      it 'redirects to the created audio' do
        post audios_url, params: { audio: valid_attributes }
        expect(response).to redirect_to(audio_url(Audio.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Audio' do
        expect do
          post audios_url, params: { audio: invalid_attributes }
        end.not_to change(Audio, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post audios_url, params: { audio: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested audio' do
        audio = Audio.create! valid_attributes
        patch audio_url(audio), params: { audio: new_attributes }
        audio.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the audio' do
        audio = Audio.create! valid_attributes
        patch audio_url(audio), params: { audio: new_attributes }
        audio.reload
        expect(response).to redirect_to(audio_url(audio))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        audio = Audio.create! valid_attributes
        patch audio_url(audio), params: { audio: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested audio' do
      audio = Audio.create! valid_attributes
      expect do
        delete audio_url(audio)
      end.to change(Audio, :count).by(-1)
    end

    it 'redirects to the audios list' do
      audio = Audio.create! valid_attributes
      delete audio_url(audio)
      expect(response).to redirect_to(audios_url)
    end
  end
end
