default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: mixtape_club_development

test:
  <<: *default
  host: localhost
  database: mixtape_club_test

production:
  <<: *default
  database: mixtape_club_production
  username: mixtape_club
  password: <%= ENV.fetch('MIXTAPE_CLUB_DATABASE_PASSWORD', '') %>
