#!/usr/bin/env ruby

# script/seed: Drop the database, rebuild it, and fill it with seed data

require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('..', __dir__)

def system! *args
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  puts '==> Dropping DB…'
  system! 'bundle exec rails db:drop'

  puts '==> Creating DB…'
  system! 'bundle exec rails db:create'

  puts '==> Migrating DB…'
  system! 'bundle exec rails db:migrate'

  puts '==> Seeds local development DB…'
  system! 'bundle exec rake db:seed'
  puts

  puts '==> All done!'
end
